# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    build:
      html:
        - echo "Extracting pre-built docs from docs.zip"
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - unzip -o docs.zip -d $READTHEDOCS_OUTPUT/html/
      htmlzip:
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip/
        - cp docs.zip $READTHEDOCS_OUTPUT/htmlzip/document.zip
      pdf:
        - mkdir -p $READTHEDOCS_OUTPUT/pdf/
        - unzip -o docs.zip "latex/*.pdf" -d temp/ || echo "No PDF found"
        - find temp/ -name "*.pdf" -exec cp {} $READTHEDOCS_OUTPUT/pdf/document.pdf \; || echo "No PDF to copy"
        - rm -rf temp/
