name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    types: [opened, reopened, synchronize]
  schedule:
    # Weekly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  test:
    name: Franken+LAMMPS (metatomic)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      # More info on options: https://github.com/marketplace/actions/setup-micromamba
      - name: Create and setup mamba 
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: .github/env-dev.yml
          environment-name: train

      - name: Create lammps environment
        shell: bash -l {0}
        run: |
          micromamba create -y -n lammps -f .github/env-lammps-metatomic.yml
          micromamba list -n lammps

      - name: Debug lammps env
        shell: bash -l {0}
        run: |
          micromamba run -n lammps bash -lc '
            echo "PATH=$PATH"
            ls -la $CONDA_PREFIX/bin | grep -E "lmp|lammps" || true
            which lmp || true
            which lammps || true
          '

      - name: Install package
        shell: bash -l {0}
        run: |
          micromamba run -n train python -m pip install . --no-deps
          micromamba list -n train

      # - name: Train franken model
      #   shell: bash -l {0}
      #   run: |
      #     micromamba run -n train bash tests/lammps/metatomic/train_and_compile.sh

      - name: Run with lammps
        shell: bash -l {0}
        run: |
          micromamba run -n lammps bash -lc "cd tests/lammps/metatomic/ && lmp -i lammps_metatomic.in"

