name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Linting with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          use_pyproject: true
      - name: Run Ruff
        run: ruff check --output-format=github .
